package sample.drools.role

import java.math.BigDecimal
import sample.drools.Sample1.Product

rule "Offer for Diamond"
    when
            productObject : Product(type=="diamond")
    then
            productObject.setDiscount(new BigDecimal(15));
    end
rule "Offer for Gold"
    when
            productObject : Product(type=="gold")
    then
            productObject.setDiscount(new BigDecimal(25));
    end